<?xml version="1.0" encoding="utf-8"?><Database Name="ODP_Taxonomy_Dev" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=2sql235;Initial Catalog=ODP_Taxonomy_Dev;User ID=odpTaxonomy" SettingsObjectName="ODPTaxonomyDAL_TT.Properties.Settings" SettingsPropertyName="ODP_Taxonomy_DevConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Users" Member="tbl_aspnet_Users">
    <Type Name="tbl_aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserFirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserLastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_aspnet_User_tbl_aspnet_UsersInRole" Member="tbl_aspnet_UsersInRoles" Storage="_aspnet_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="tbl_aspnet_UsersInRole" />
      <Association Name="tbl_aspnet_User_tbl_aspnet_Membership" Member="tbl_aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="tbl_aspnet_Membership" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersInRoles" Member="tbl_aspnet_UsersInRoles">
    <Type Name="tbl_aspnet_UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tbl_aspnet_User_tbl_aspnet_UsersInRole" Member="tbl_aspnet_User" Storage="_aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="tbl_aspnet_User" IsForeignKey="true" />
      <Association Name="tbl_aspnet_Role_tbl_aspnet_UsersInRole" Member="tbl_aspnet_Role" ThisKey="RoleId" OtherKey="RoleId" Type="tbl_aspnet_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TeamType" Member="tbl_TeamTypes">
    <Type Name="tbl_TeamType">
      <Column Name="TeamTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamType" Member="TeamType1" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="tbl_TeamType_tbl_Team" Member="tbl_Teams" ThisKey="TeamTypeID" OtherKey="TeamTypeID" Type="tbl_Team" />
    </Type>
  </Table>
  <Table Name="dbo.TeamUser" Member="tbl_TeamUsers">
    <Type Name="tbl_TeamUser">
      <Column Name="TeamID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tbl_Team_tbl_TeamUser" Member="tbl_Team" ThisKey="TeamID" OtherKey="TeamID" Type="tbl_Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="tbl_Status">
    <Type Name="tbl_Status">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Member="Status1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="tbl_Status_tbl_A_StudyFocus" Member="tbl_A_StudyFocus" Storage="_A_StudyFocus" ThisKey="StatusID" OtherKey="StatusID" Type="tbl_A_StudyFocus" />
      <Association Name="tbl_Status_tbL_Submission" Member="Submissions" ThisKey="StatusID" OtherKey="StatusID" Type="tbL_Submission" />
      <Association Name="tbl_Status_tbL_Submission1" Member="tbL_Submissions" Storage="_tbl_Submissions" ThisKey="StatusID" OtherKey="StatusID" Type="tbL_Submission" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="tbl_aspnet_Memberships">
    <Type Name="tbl_aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tbl_aspnet_User_tbl_aspnet_Membership" Member="tbl_aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="tbl_aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="tbl_Teams">
    <Type Name="tbl_Team">
      <Column Name="TeamID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TeamTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Createdby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_Team_tbl_TeamUser" Member="tbl_TeamUsers" ThisKey="TeamID" OtherKey="TeamID" Type="tbl_TeamUser" />
      <Association Name="tbl_Team_tbl_Evaluation" Member="tbl_Evaluations" ThisKey="TeamID" OtherKey="TeamID" Type="tbl_Evaluation" />
      <Association Name="tbl_TeamType_tbl_Team" Member="tbl_TeamType" ThisKey="TeamTypeID" OtherKey="TeamTypeID" Type="tbl_TeamType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Evaluation" Member="tbl_Evaluations">
    <Type Name="tbl_Evaluation">
      <Column Name="EvaluationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ConsensusStartedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AbstractID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsComplete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateTimeStarted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateTimeEnded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EvaluationTypeId" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IsStopped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StoppedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StoppedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_Evaluation_tbl_AbstractScan" Member="tbl_AbstractScans" ThisKey="EvaluationId" OtherKey="EvaluationId" Type="tbl_AbstractScan" />
      <Association Name="tbl_Evaluation_tbl_AbstractStatusChangeHistory" Member="AbstractStatusChangeHistories" ThisKey="EvaluationId" OtherKey="EvaluationId" Type="tbl_AbstractStatusChangeHistory" />
      <Association Name="tbl_Evaluation_tbl_AbstractStatusChangeHistory1" Member="tbl_AbstractStatusChangeHistories" ThisKey="EvaluationId" OtherKey="EvaluationId" Type="tbl_AbstractStatusChangeHistory" />
      <Association Name="tbl_Evaluation_tbL_Submission" Member="tbL_Submissions" Storage="_tbl_Submissions" ThisKey="EvaluationId" OtherKey="EvaluationId" Type="tbL_Submission" />
      <Association Name="tbl_Team_tbl_Evaluation" Member="tbl_Team" ThisKey="TeamID" OtherKey="TeamID" Type="tbl_Team" IsForeignKey="true" />
      <Association Name="tbl_EvaluationType_tbl_Evaluation" Member="tbl_EvaluationType" ThisKey="EvaluationTypeId" OtherKey="EvaluationTypeId" Type="tbl_EvaluationType" IsForeignKey="true" />
      <Association Name="tbl_Abstract_tbl_Evaluation" Member="Abstract" ThisKey="AbstractID" OtherKey="AbstractID" Type="tbl_Abstract" IsForeignKey="true" />
      <Association Name="tbl_Abstract_tbl_Evaluation1" Member="tbl_Abstract" ThisKey="AbstractID" OtherKey="AbstractID" Type="tbl_Abstract" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AbstractStatus" Member="tbl_AbstractStatus">
    <Type Name="tbl_AbstractStatus">
      <Column Name="AbstractStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AbstractStatusCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AbstractStatusDescription" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_AbstractStatus_tbl_AbstractStatusChangeHistory" Member="tbl_AbstractStatusChangeHistories" ThisKey="AbstractStatusID" OtherKey="AbstractStatusID" Type="tbl_AbstractStatusChangeHistory" />
    </Type>
  </Table>
  <Table Name="dbo.AbstractScan" Member="tbl_AbstractScans">
    <Type Name="tbl_AbstractScan">
      <Column Name="AbstractScanID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EvaluationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="UploadedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UploadedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_Evaluation_tbl_AbstractScan" Member="tbl_Evaluation" ThisKey="EvaluationId" OtherKey="EvaluationId" Type="tbl_Evaluation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AbstractStatusChangeHistory" Member="tbl_AbstractStatusChangeHistories">
    <Type Name="tbl_AbstractStatusChangeHistory">
      <Column Name="AbstractStatusChangeHistoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AbstractID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EvaluationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AbstractStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="tbl_AbstractStatus_tbl_AbstractStatusChangeHistory" Member="tbl_AbstractStatus" ThisKey="AbstractStatusID" OtherKey="AbstractStatusID" Type="tbl_AbstractStatus" IsForeignKey="true" />
      <Association Name="tbl_Evaluation_tbl_AbstractStatusChangeHistory" Member="tbl_Evaluation" ThisKey="EvaluationId" OtherKey="EvaluationId" Type="tbl_Evaluation" IsForeignKey="true" />
      <Association Name="tbl_Evaluation_tbl_AbstractStatusChangeHistory1" Member="tbl_Evaluation1" ThisKey="EvaluationId" OtherKey="EvaluationId" Type="tbl_Evaluation" IsForeignKey="true" />
      <Association Name="tbl_Abstract_tbl_AbstractStatusChangeHistory" Member="tbl_Abstract" ThisKey="AbstractID" OtherKey="AbstractID" Type="tbl_Abstract" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AbstractTopic" Member="tbl_AbstractTopics">
    <Type Name="tbl_AbstractTopic">
      <Column Name="AbstractID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudyFocusID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tbl_A_StudyFocus_tbl_AbstractTopic" Member="tbl_A_StudyFocus" Storage="_A_StudyFocus" ThisKey="StudyFocusID" OtherKey="StudyFocusID" Type="tbl_A_StudyFocus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EvaluationType" Member="tbl_EvaluationTypes">
    <Type Name="tbl_EvaluationType" Modifier="Abstract">
      <Column Name="EvaluationTypeId" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EvaluationType" Member="EvaluationType1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_EvaluationType_tbl_Evaluation" Member="tbl_Evaluations" ThisKey="EvaluationTypeId" OtherKey="EvaluationTypeId" Type="tbl_Evaluation" />
    </Type>
  </Table>
  <Table Name="dbo.A_StudyFocus" Member="tbl_A_StudyFocus">
    <Type Name="tbl_A_StudyFocus">
      <Column Name="StudyFocusID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudyFocus" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A1_IsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="A2_IsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="A3_IsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AbstractStudyFocusSort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowAsAbstractTopic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_A_StudyFocus_tbl_AbstractTopic" Member="tbl_AbstractTopics" ThisKey="StudyFocusID" OtherKey="StudyFocusID" Type="tbl_AbstractTopic" />
      <Association Name="tbl_Status_tbl_A_StudyFocus" Member="tbl_Status" ThisKey="StatusID" OtherKey="StatusID" Type="tbl_Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Submission" Member="tbL_Submissions">
    <Type Name="tbL_Submission">
      <Column Name="SubmissionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EvaluationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SubmissionTypeId" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnableToCode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ApproveSupervisorUserID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SubmissionDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_Evaluation_tbL_Submission" Member="tbl_Evaluation" ThisKey="EvaluationId" OtherKey="EvaluationId" Type="tbl_Evaluation" IsForeignKey="true" />
      <Association Name="tbl_Status_tbL_Submission" Member="tbl_Status" ThisKey="StatusID" OtherKey="StatusID" Type="tbl_Status" IsForeignKey="true" />
      <Association Name="tbl_Status_tbL_Submission1" Member="tbl_Status1" ThisKey="StatusID" OtherKey="StatusID" Type="tbl_Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="tbl_aspnet_Roles">
    <Type Name="tbl_aspnet_Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DisplayRoleName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="tbl_aspnet_Role_tbl_aspnet_UsersInRole" Member="tbl_aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="tbl_aspnet_UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.Abstract" Member="tbl_Abstracts">
    <Type Name="tbl_Abstract">
      <Column Name="AbstractID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdministeringIC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Abstract" Member="Abstract1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AbstractDescPart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AbstractPublicHeathPart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AbstractNIHPart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AbstractProjTermPart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Activity" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ProjectNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupportYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Suffix" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PIProjectLeader" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LastExportDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_Abstract_tbl_Evaluation" Member="tbl_Evaluations" ThisKey="AbstractID" OtherKey="AbstractID" Type="tbl_Evaluation" />
      <Association Name="tbl_Abstract_tbl_Evaluation1" Member="tbl_Evaluations1" ThisKey="AbstractID" OtherKey="AbstractID" Type="tbl_Evaluation" />
      <Association Name="tbl_Abstract_tbl_AbstractStatusChangeHistory" Member="tbl_AbstractStatusChangeHistories" ThisKey="AbstractID" OtherKey="AbstractID" Type="tbl_AbstractStatusChangeHistory" />
    </Type>
  </Table>
  <Function Name="dbo.select_abstract_status_tt" Method="select_abstract_status_tt">
    <Parameter Name="AbstractID" Parameter="abstractID" Type="System.Int32" DbType="Int" />
    <ElementType Name="select_abstract_status_ttResult">
      <Column Name="AbstractStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.KappaUserIdentify_Insert_ByTeamID" Method="KappaUserIdentify_Insert_ByTeamID">
    <Parameter Name="TeamID" Parameter="teamID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.select_abstracts_group_tt" Method="select_abstracts_group_tt">
    <ElementType Name="select_abstracts_group_ttResult">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sorting" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_abstracts_no_reopen_tt" Method="select_abstracts_no_reopen_tt">
    <ElementType Name="select_abstracts_no_reopen_ttResult">
      <Column Name="AbstractID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_abstracts_coding_tt" Method="select_abstracts_coding_tt">
    <Parameter Name="AbstractStatusID" Parameter="abstractStatusID" Type="System.Int32" DbType="Int" />
    <ElementType Name="select_abstracts_coding_ttResult">
      <Column Name="AbstractID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_abstractId_team_member_tt" Method="select_abstractId_team_member_tt">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="select_abstractId_team_member_ttResult">
      <Column Name="AbstractID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.rpt_AbstractExported" Method="rpt_AbstractExported">
    <Parameter Name="AbstractID" Parameter="abstractID" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="rpt_AbstractExportedResult">
      <Column Name="ApplicationID_Data_exported" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Exported Date]" Member="Exported_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.rpt_AbstractStatusTrail" Method="rpt_AbstractStatusTrail">
    <Parameter Name="AbstractID" Parameter="abstractID" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="rpt_AbstractStatusTrailResult">
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PIProjectLeader" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AbstractStatusCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AbstractStatusDescription" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[rpt_Cdr_ODP IndividualCoding]" Method="rpt_Cdr_ODP_IndividualCoding">
    <Parameter Name="AbstractID" Parameter="abstractID" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="rpt_Cdr_ODP_IndividualCodingResult">
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PIProjectLeader" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MainSection" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubSection" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SectionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CdrA" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CdrB" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CdrC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CdrConsensus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ODPA" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ODPB" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ODPC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ODPConsensus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ConsensusReconciled" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Final Consensus]" Member="Final_Consensus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.rpt_KappaData" Method="rpt_KappaData">
    <Parameter Name="AbstractID" Parameter="abstractID" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="rpt_KappaDataResult">
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PIProjectLeader" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="KappaType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="A1" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="A2" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="A3" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="B" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="C" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="D" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="E" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="F" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="CdrKappaDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ODPKappaDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.rpt_Team_User_UC" Method="rpt_Team_User_UC">
    <Parameter Name="AbstractID" Parameter="abstractID" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="rpt_Team_User_UCResult">
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PIProjectLeader" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TeamCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TeamType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UserAlias" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SubmissionType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UnableToCode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.rpt_OPA" Method="rpt_OPA">
    <Parameter Name="AbstractID" Parameter="abstractID" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="rpt_OPAResult">
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PIProjectLeader" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MainSection" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubSection" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SectionName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Final Consensus]" Member="Final_Consensus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.rpt_Cdr_ODPNotesPDF" Method="rpt_Cdr_ODPNotesPDF">
    <Parameter Name="AbstractID" Parameter="abstractID" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Domain" Parameter="domain" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="rpt_Cdr_ODPNotesPDFResult">
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PIProjectLeader" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProjectTitle" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(393)" CanBeNull="true" />
      <Column Name="EvaluationType" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.start_abstract_coding_tt" Method="start_abstract_coding_tt">
    <Parameter Name="TeamID" Parameter="teamID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="AbstractID" Parameter="abstractID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="EvaluationId" Parameter="evaluationId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="IsAbstractTaken" Parameter="isAbstractTaken" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="IsAbstractAvailable" Parameter="isAbstractAvailable" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>