#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPTaxonomyDAL_ST
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ODP_Taxonomy_Dev")]
	public partial class ReportingAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ReportingAppDataContext() : 
				base(global::ODPTaxonomyDAL_ST.Properties.Settings.Default.ODP_Taxonomy_DevConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Report_QC_Week> Report_QC_Weeks
		{
			get
			{
				return this.GetTable<Report_QC_Week>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_KappaAvg_ByQCWeeks")]
		public ISingleResult<Report_KappaAvg_ByQCWeeksResult> Report_KappaAvg_ByQCWeeks([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCStartWeek", DbType="VarChar(100)")] string qCStartWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCEndWeek", DbType="VarChar(100)")] string qCEndWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KType", DbType="VarChar(10)")] string kType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qCStartWeek, qCEndWeek, kType);
			return ((ISingleResult<Report_KappaAvg_ByQCWeeksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_KappaE7F6_ByQCWeeks")]
		public ISingleResult<Report_KappaE7F6_ByQCWeeksResult> Report_KappaE7F6_ByQCWeeks([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCStartWeek", DbType="VarChar(100)")] string qCStartWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCEndWeek", DbType="VarChar(100)")] string qCEndWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KType", DbType="VarChar(10)")] string kType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qCStartWeek, qCEndWeek, kType);
			return ((ISingleResult<Report_KappaE7F6_ByQCWeeksResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Report_QC_Week")]
	public partial class Report_QC_Week
	{
		
		private int _QC_ID;
		
		private string _QC_week;
		
		private string _Dates_IQ_Coded;
		
		private System.Nullable<int> _Rpt_Year;
		
		private System.Nullable<int> _Rpt_Month;
		
		public Report_QC_Week()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_ID", DbType="Int NOT NULL")]
		public int QC_ID
		{
			get
			{
				return this._QC_ID;
			}
			set
			{
				if ((this._QC_ID != value))
				{
					this._QC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_week", DbType="NVarChar(20)")]
		public string QC_week
		{
			get
			{
				return this._QC_week;
			}
			set
			{
				if ((this._QC_week != value))
				{
					this._QC_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dates_IQ_Coded", DbType="NVarChar(50)")]
		public string Dates_IQ_Coded
		{
			get
			{
				return this._Dates_IQ_Coded;
			}
			set
			{
				if ((this._Dates_IQ_Coded != value))
				{
					this._Dates_IQ_Coded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rpt_Year", DbType="Int")]
		public System.Nullable<int> Rpt_Year
		{
			get
			{
				return this._Rpt_Year;
			}
			set
			{
				if ((this._Rpt_Year != value))
				{
					this._Rpt_Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rpt_Month", DbType="Int")]
		public System.Nullable<int> Rpt_Month
		{
			get
			{
				return this._Rpt_Month;
			}
			set
			{
				if ((this._Rpt_Month != value))
				{
					this._Rpt_Month = value;
				}
			}
		}
	}
	
	public partial class Report_KappaAvg_ByQCWeeksResult
	{
		
		private string _QCWeek;
		
		private string _IQDate;
		
		private System.Nullable<int> _KappaTypeID;
		
		private System.Nullable<int> _NumbAbs;
		
		private System.Nullable<decimal> _A1;
		
		private System.Nullable<decimal> _A2;
		
		private System.Nullable<decimal> _A3;
		
		private System.Nullable<decimal> _B;
		
		private System.Nullable<decimal> _C;
		
		private System.Nullable<decimal> _D;
		
		private System.Nullable<decimal> _E;
		
		private System.Nullable<decimal> _F;
		
		public Report_KappaAvg_ByQCWeeksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QCWeek", DbType="VarChar(10)")]
		public string QCWeek
		{
			get
			{
				return this._QCWeek;
			}
			set
			{
				if ((this._QCWeek != value))
				{
					this._QCWeek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQDate", DbType="VarChar(100)")]
		public string IQDate
		{
			get
			{
				return this._IQDate;
			}
			set
			{
				if ((this._IQDate != value))
				{
					this._IQDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KappaTypeID", DbType="Int")]
		public System.Nullable<int> KappaTypeID
		{
			get
			{
				return this._KappaTypeID;
			}
			set
			{
				if ((this._KappaTypeID != value))
				{
					this._KappaTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumbAbs", DbType="Int")]
		public System.Nullable<int> NumbAbs
		{
			get
			{
				return this._NumbAbs;
			}
			set
			{
				if ((this._NumbAbs != value))
				{
					this._NumbAbs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> A1
		{
			get
			{
				return this._A1;
			}
			set
			{
				if ((this._A1 != value))
				{
					this._A1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> A2
		{
			get
			{
				return this._A2;
			}
			set
			{
				if ((this._A2 != value))
				{
					this._A2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A3", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> A3
		{
			get
			{
				return this._A3;
			}
			set
			{
				if ((this._A3 != value))
				{
					this._A3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this._B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this._C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> F
		{
			get
			{
				return this._F;
			}
			set
			{
				if ((this._F != value))
				{
					this._F = value;
				}
			}
		}
	}
	
	public partial class Report_KappaE7F6_ByQCWeeksResult
	{
		
		private string _QC_week;
		
		private string _Dates_IQ_Coded;
		
		private System.Nullable<int> _KappaTypeID;
		
		private System.Nullable<int> _totalAbs;
		
		public Report_KappaE7F6_ByQCWeeksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_week", DbType="NVarChar(20)")]
		public string QC_week
		{
			get
			{
				return this._QC_week;
			}
			set
			{
				if ((this._QC_week != value))
				{
					this._QC_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dates_IQ_Coded", DbType="NVarChar(50)")]
		public string Dates_IQ_Coded
		{
			get
			{
				return this._Dates_IQ_Coded;
			}
			set
			{
				if ((this._Dates_IQ_Coded != value))
				{
					this._Dates_IQ_Coded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KappaTypeID", DbType="Int")]
		public System.Nullable<int> KappaTypeID
		{
			get
			{
				return this._KappaTypeID;
			}
			set
			{
				if ((this._KappaTypeID != value))
				{
					this._KappaTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalAbs", DbType="Int")]
		public System.Nullable<int> totalAbs
		{
			get
			{
				return this._totalAbs;
			}
			set
			{
				if ((this._totalAbs != value))
				{
					this._totalAbs = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
