#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPTaxonomyDAL_ST
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ODP_Taxonomy_Dev")]
	public partial class ReportingAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ReportingAppDataContext() : 
				base(global::ODPTaxonomyDAL_ST.Properties.Settings.Default.ODP_Taxonomy_DevConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Report_QC_Week> Report_QC_Weeks
		{
			get
			{
				return this.GetTable<Report_QC_Week>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_KappaAvg_ByQCWeeks")]
		public ISingleResult<Report_KappaAvg_ByQCWeeksResult> Report_KappaAvg_ByQCWeeks([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCStartWeek", DbType="VarChar(100)")] string qCStartWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCEndWeek", DbType="VarChar(100)")] string qCEndWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KType", DbType="VarChar(10)")] string kType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qCStartWeek, qCEndWeek, kType);
			return ((ISingleResult<Report_KappaAvg_ByQCWeeksResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Report_QC_Week")]
	public partial class Report_QC_Week
	{
		
		private System.Nullable<double> _QC_ID;
		
		private string _QC_week;
		
		private string _Dates_IQ_Coded;
		
		private System.Nullable<double> _Rpt_Year;
		
		private System.Nullable<double> _Rpt_Month;
		
		public Report_QC_Week()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_ID", DbType="Float")]
		public System.Nullable<double> QC_ID
		{
			get
			{
				return this._QC_ID;
			}
			set
			{
				if ((this._QC_ID != value))
				{
					this._QC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_week", DbType="NVarChar(255)")]
		public string QC_week
		{
			get
			{
				return this._QC_week;
			}
			set
			{
				if ((this._QC_week != value))
				{
					this._QC_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dates_IQ_Coded", DbType="NVarChar(255)")]
		public string Dates_IQ_Coded
		{
			get
			{
				return this._Dates_IQ_Coded;
			}
			set
			{
				if ((this._Dates_IQ_Coded != value))
				{
					this._Dates_IQ_Coded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rpt_Year", DbType="Float")]
		public System.Nullable<double> Rpt_Year
		{
			get
			{
				return this._Rpt_Year;
			}
			set
			{
				if ((this._Rpt_Year != value))
				{
					this._Rpt_Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rpt_Month", DbType="Float")]
		public System.Nullable<double> Rpt_Month
		{
			get
			{
				return this._Rpt_Month;
			}
			set
			{
				if ((this._Rpt_Month != value))
				{
					this._Rpt_Month = value;
				}
			}
		}
	}
	
	public partial class Report_KappaAvg_ByQCWeeksResult
	{
		
		private string _QC_week;
		
		private string _IQ_StartDate;
		
		private string _IQ_EndDate;
		
		private string _Kappa;
		
		private System.Nullable<int> _E7F6Ct;
		
		private System.Nullable<int> _Number_Abs;
		
		private string _A1;
		
		private string _A2;
		
		private string _A3;
		
		private string _B;
		
		private string _C;
		
		private string _D;
		
		private string _E;
		
		private string _F;
		
		public Report_KappaAvg_ByQCWeeksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_week", DbType="NVarChar(20)")]
		public string QC_week
		{
			get
			{
				return this._QC_week;
			}
			set
			{
				if ((this._QC_week != value))
				{
					this._QC_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_StartDate", DbType="NVarChar(50)")]
		public string IQ_StartDate
		{
			get
			{
				return this._IQ_StartDate;
			}
			set
			{
				if ((this._IQ_StartDate != value))
				{
					this._IQ_StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_EndDate", DbType="NVarChar(50)")]
		public string IQ_EndDate
		{
			get
			{
				return this._IQ_EndDate;
			}
			set
			{
				if ((this._IQ_EndDate != value))
				{
					this._IQ_EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kappa", DbType="VarChar(10)")]
		public string Kappa
		{
			get
			{
				return this._Kappa;
			}
			set
			{
				if ((this._Kappa != value))
				{
					this._Kappa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E7F6Ct", DbType="Int")]
		public System.Nullable<int> E7F6Ct
		{
			get
			{
				return this._E7F6Ct;
			}
			set
			{
				if ((this._E7F6Ct != value))
				{
					this._E7F6Ct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number_Abs", DbType="Int")]
		public System.Nullable<int> Number_Abs
		{
			get
			{
				return this._Number_Abs;
			}
			set
			{
				if ((this._Number_Abs != value))
				{
					this._Number_Abs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1", DbType="NVarChar(30)")]
		public string A1
		{
			get
			{
				return this._A1;
			}
			set
			{
				if ((this._A1 != value))
				{
					this._A1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2", DbType="NVarChar(30)")]
		public string A2
		{
			get
			{
				return this._A2;
			}
			set
			{
				if ((this._A2 != value))
				{
					this._A2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A3", DbType="NVarChar(30)")]
		public string A3
		{
			get
			{
				return this._A3;
			}
			set
			{
				if ((this._A3 != value))
				{
					this._A3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="NVarChar(30)")]
		public string B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this._B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="NVarChar(30)")]
		public string C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this._C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="NVarChar(30)")]
		public string D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="NVarChar(30)")]
		public string E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F", DbType="NVarChar(30)")]
		public string F
		{
			get
			{
				return this._F;
			}
			set
			{
				if ((this._F != value))
				{
					this._F = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
