#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODPTaxonomyDAL_ST
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ODP_Taxonomy_DEV")]
	public partial class ReportingAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMechanism_Type(Mechanism_Type instance);
    partial void UpdateMechanism_Type(Mechanism_Type instance);
    partial void DeleteMechanism_Type(Mechanism_Type instance);
    #endregion
		
		public ReportingAppDataContext() : 
				base(global::ODPTaxonomyDAL_ST.Properties.Settings.Default.ODP_Taxonomy_DEVConnectionString7, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportingAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Report_QC_Week> Report_QC_Weeks
		{
			get
			{
				return this.GetTable<Report_QC_Week>();
			}
		}
		
		public System.Data.Linq.Table<Mechanism_Type> Mechanism_Types
		{
			get
			{
				return this.GetTable<Mechanism_Type>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_KappaAvg_ByQCWeeks")]
		public ISingleResult<Report_KappaAvg_ByQCWeeksResult> Report_KappaAvg_ByQCWeeks([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCStartWeek", DbType="VarChar(100)")] string qCStartWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCEndWeek", DbType="VarChar(100)")] string qCEndWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KType", DbType="VarChar(10)")] string kType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qCStartWeek, qCEndWeek, kType);
			return ((ISingleResult<Report_KappaAvg_ByQCWeeksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_KappaAvg_DataDetail_ByQCWeeks")]
		public ISingleResult<Report_KappaAvg_DataDetail_ByQCWeeksResult> Report_KappaAvg_DataDetail_ByQCWeeks([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCStartWeek", DbType="VarChar(100)")] string qCStartWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCEndWeek", DbType="VarChar(100)")] string qCEndWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KType", DbType="VarChar(10)")] string kType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qCStartWeek, qCEndWeek, kType);
			return ((ISingleResult<Report_KappaAvg_DataDetail_ByQCWeeksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_KappaDatapulling")]
		public ISingleResult<Report_KappaDatapullingResult> Report_KappaDatapulling([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FY", DbType="VarChar(20)")] string fY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fY);
			return ((ISingleResult<Report_KappaDatapullingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_KappaAvg_ByQCWeeks_New")]
		public ISingleResult<Report_KappaAvg_ByQCWeeks_NewResult> Report_KappaAvg_ByQCWeeks_New([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCStartWeek", DbType="VarChar(100)")] string qCStartWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCEndWeek", DbType="VarChar(100)")] string qCEndWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KType", DbType="VarChar(10)")] string kType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MechanismType", DbType="Int")] System.Nullable<int> mechanismType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qCStartWeek, qCEndWeek, kType, mechanismType);
			return ((ISingleResult<Report_KappaAvg_ByQCWeeks_NewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_AbstractSummary")]
		public ISingleResult<Report_AbstractSummaryResult> Report_AbstractSummary()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Report_AbstractSummaryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_AbstractSummary_Merge")]
		public ISingleResult<Report_AbstractSummary_MergeResult> Report_AbstractSummary_Merge()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Report_AbstractSummary_MergeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_KappaAvg_DataDetail_ByQCWeeks_New")]
		public ISingleResult<Report_KappaAvg_DataDetail_ByQCWeeks_NewResult> Report_KappaAvg_DataDetail_ByQCWeeks_New([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCStartWeek", DbType="VarChar(100)")] string qCStartWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QCEndWeek", DbType="VarChar(100)")] string qCEndWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KType", DbType="VarChar(10)")] string kType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MechanismType", DbType="VarChar(1000)")] string mechanismType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qCStartWeek, qCEndWeek, kType, mechanismType);
			return ((ISingleResult<Report_KappaAvg_DataDetail_ByQCWeeks_NewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Report_SelectionDatapulling")]
		public ISingleResult<Report_SelectionDatapullingResult> Report_SelectionDatapulling([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FY", DbType="VarChar(20)")] string fY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fY);
			return ((ISingleResult<Report_SelectionDatapullingResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Report_QC_Week")]
	public partial class Report_QC_Week
	{
		
		private System.Nullable<int> _QC_ID;
		
		private string _QC_week;
		
		private string _Dates_IQ_Coded;
		
		private System.Nullable<double> _Rpt_Year;
		
		private System.Nullable<double> _Rpt_Month;
		
		public Report_QC_Week()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_ID", DbType="Int")]
		public System.Nullable<int> QC_ID
		{
			get
			{
				return this._QC_ID;
			}
			set
			{
				if ((this._QC_ID != value))
				{
					this._QC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_week", DbType="NVarChar(255)")]
		public string QC_week
		{
			get
			{
				return this._QC_week;
			}
			set
			{
				if ((this._QC_week != value))
				{
					this._QC_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dates_IQ_Coded", DbType="NVarChar(255)")]
		public string Dates_IQ_Coded
		{
			get
			{
				return this._Dates_IQ_Coded;
			}
			set
			{
				if ((this._Dates_IQ_Coded != value))
				{
					this._Dates_IQ_Coded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rpt_Year", DbType="Float")]
		public System.Nullable<double> Rpt_Year
		{
			get
			{
				return this._Rpt_Year;
			}
			set
			{
				if ((this._Rpt_Year != value))
				{
					this._Rpt_Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rpt_Month", DbType="Float")]
		public System.Nullable<double> Rpt_Month
		{
			get
			{
				return this._Rpt_Month;
			}
			set
			{
				if ((this._Rpt_Month != value))
				{
					this._Rpt_Month = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mechanism_Type")]
	public partial class Mechanism_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mechanism_TypeID;
		
		private string _Mechanism_Type1;
		
		private System.Nullable<int> _Type;
		
		private string _Mechanism;
		
		private System.Nullable<int> _StatusID;
		
		private System.Nullable<int> _Sorting;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMechanism_TypeIDChanging(int value);
    partial void OnMechanism_TypeIDChanged();
    partial void OnMechanism_Type1Changing(string value);
    partial void OnMechanism_Type1Changed();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnMechanismChanging(string value);
    partial void OnMechanismChanged();
    partial void OnStatusIDChanging(System.Nullable<int> value);
    partial void OnStatusIDChanged();
    partial void OnSortingChanging(System.Nullable<int> value);
    partial void OnSortingChanged();
    #endregion
		
		public Mechanism_Type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mechanism_TypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mechanism_TypeID
		{
			get
			{
				return this._Mechanism_TypeID;
			}
			set
			{
				if ((this._Mechanism_TypeID != value))
				{
					this.OnMechanism_TypeIDChanging(value);
					this.SendPropertyChanging();
					this._Mechanism_TypeID = value;
					this.SendPropertyChanged("Mechanism_TypeID");
					this.OnMechanism_TypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Mechanism_Type", Storage="_Mechanism_Type1", DbType="NVarChar(20)")]
		public string Mechanism_Type1
		{
			get
			{
				return this._Mechanism_Type1;
			}
			set
			{
				if ((this._Mechanism_Type1 != value))
				{
					this.OnMechanism_Type1Changing(value);
					this.SendPropertyChanging();
					this._Mechanism_Type1 = value;
					this.SendPropertyChanged("Mechanism_Type1");
					this.OnMechanism_Type1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mechanism", DbType="NVarChar(20)")]
		public string Mechanism
		{
			get
			{
				return this._Mechanism;
			}
			set
			{
				if ((this._Mechanism != value))
				{
					this.OnMechanismChanging(value);
					this.SendPropertyChanging();
					this._Mechanism = value;
					this.SendPropertyChanged("Mechanism");
					this.OnMechanismChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int")]
		public System.Nullable<int> StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this.OnStatusIDChanging(value);
					this.SendPropertyChanging();
					this._StatusID = value;
					this.SendPropertyChanged("StatusID");
					this.OnStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sorting", DbType="Int")]
		public System.Nullable<int> Sorting
		{
			get
			{
				return this._Sorting;
			}
			set
			{
				if ((this._Sorting != value))
				{
					this.OnSortingChanging(value);
					this.SendPropertyChanging();
					this._Sorting = value;
					this.SendPropertyChanged("Sorting");
					this.OnSortingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Report_KappaAvg_ByQCWeeksResult
	{
		
		private string _QC_week;
		
		private string _IQ_StartDate;
		
		private string _IQ_EndDate;
		
		private string _Kappa;
		
		private System.Nullable<int> _E7F6Ct;
		
		private System.Nullable<int> _Number_Abs;
		
		private string _A1;
		
		private string _A2;
		
		private string _A3;
		
		private string _B;
		
		private string _C;
		
		private string _D;
		
		private string _E;
		
		private string _F;
		
		private string _Weekly_Avg;
		
		public Report_KappaAvg_ByQCWeeksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_week", DbType="NVarChar(20)")]
		public string QC_week
		{
			get
			{
				return this._QC_week;
			}
			set
			{
				if ((this._QC_week != value))
				{
					this._QC_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_StartDate", DbType="NVarChar(50)")]
		public string IQ_StartDate
		{
			get
			{
				return this._IQ_StartDate;
			}
			set
			{
				if ((this._IQ_StartDate != value))
				{
					this._IQ_StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_EndDate", DbType="NVarChar(50)")]
		public string IQ_EndDate
		{
			get
			{
				return this._IQ_EndDate;
			}
			set
			{
				if ((this._IQ_EndDate != value))
				{
					this._IQ_EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kappa", DbType="VarChar(10)")]
		public string Kappa
		{
			get
			{
				return this._Kappa;
			}
			set
			{
				if ((this._Kappa != value))
				{
					this._Kappa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E7F6Ct", DbType="Int")]
		public System.Nullable<int> E7F6Ct
		{
			get
			{
				return this._E7F6Ct;
			}
			set
			{
				if ((this._E7F6Ct != value))
				{
					this._E7F6Ct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number_Abs", DbType="Int")]
		public System.Nullable<int> Number_Abs
		{
			get
			{
				return this._Number_Abs;
			}
			set
			{
				if ((this._Number_Abs != value))
				{
					this._Number_Abs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1", DbType="NVarChar(30)")]
		public string A1
		{
			get
			{
				return this._A1;
			}
			set
			{
				if ((this._A1 != value))
				{
					this._A1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2", DbType="NVarChar(30)")]
		public string A2
		{
			get
			{
				return this._A2;
			}
			set
			{
				if ((this._A2 != value))
				{
					this._A2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A3", DbType="NVarChar(30)")]
		public string A3
		{
			get
			{
				return this._A3;
			}
			set
			{
				if ((this._A3 != value))
				{
					this._A3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="NVarChar(30)")]
		public string B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this._B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="NVarChar(30)")]
		public string C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this._C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="NVarChar(30)")]
		public string D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="NVarChar(30)")]
		public string E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F", DbType="NVarChar(30)")]
		public string F
		{
			get
			{
				return this._F;
			}
			set
			{
				if ((this._F != value))
				{
					this._F = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekly_Avg", DbType="NVarChar(30)")]
		public string Weekly_Avg
		{
			get
			{
				return this._Weekly_Avg;
			}
			set
			{
				if ((this._Weekly_Avg != value))
				{
					this._Weekly_Avg = value;
				}
			}
		}
	}
	
	public partial class Report_KappaAvg_DataDetail_ByQCWeeksResult
	{
		
		private string _QC_week;
		
		private string _IQ_StartDate;
		
		private string _IQ_EndDate;
		
		private System.Nullable<int> _AbstractID;
		
		private System.Nullable<int> _Appl_ID;
		
		private string _PI_Name;
		
		private System.Nullable<decimal> _A1;
		
		private System.Nullable<decimal> _A2;
		
		private System.Nullable<decimal> _A3;
		
		private System.Nullable<decimal> _B;
		
		private System.Nullable<decimal> _C;
		
		private System.Nullable<decimal> _D;
		
		private System.Nullable<decimal> _E;
		
		private System.Nullable<decimal> _F;
		
		public Report_KappaAvg_DataDetail_ByQCWeeksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_week", DbType="NVarChar(20)")]
		public string QC_week
		{
			get
			{
				return this._QC_week;
			}
			set
			{
				if ((this._QC_week != value))
				{
					this._QC_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_StartDate", DbType="NVarChar(50)")]
		public string IQ_StartDate
		{
			get
			{
				return this._IQ_StartDate;
			}
			set
			{
				if ((this._IQ_StartDate != value))
				{
					this._IQ_StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_EndDate", DbType="NVarChar(50)")]
		public string IQ_EndDate
		{
			get
			{
				return this._IQ_EndDate;
			}
			set
			{
				if ((this._IQ_EndDate != value))
				{
					this._IQ_EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbstractID", DbType="Int")]
		public System.Nullable<int> AbstractID
		{
			get
			{
				return this._AbstractID;
			}
			set
			{
				if ((this._AbstractID != value))
				{
					this._AbstractID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Appl_ID", DbType="Int")]
		public System.Nullable<int> Appl_ID
		{
			get
			{
				return this._Appl_ID;
			}
			set
			{
				if ((this._Appl_ID != value))
				{
					this._Appl_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PI_Name", DbType="NVarChar(255)")]
		public string PI_Name
		{
			get
			{
				return this._PI_Name;
			}
			set
			{
				if ((this._PI_Name != value))
				{
					this._PI_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> A1
		{
			get
			{
				return this._A1;
			}
			set
			{
				if ((this._A1 != value))
				{
					this._A1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> A2
		{
			get
			{
				return this._A2;
			}
			set
			{
				if ((this._A2 != value))
				{
					this._A2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A3", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> A3
		{
			get
			{
				return this._A3;
			}
			set
			{
				if ((this._A3 != value))
				{
					this._A3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this._B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this._C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> F
		{
			get
			{
				return this._F;
			}
			set
			{
				if ((this._F != value))
				{
					this._F = value;
				}
			}
		}
	}
	
	public partial class Report_KappaDatapullingResult
	{
		
		private string _FY;
		
		private string _SubCategory;
		
		private System.Nullable<int> _ApplicationID;
		
		private string _PIProjectLeader;
		
		private string _KappaType;
		
		private System.Nullable<decimal> _A1;
		
		private System.Nullable<decimal> _A2;
		
		private System.Nullable<decimal> _A3;
		
		private System.Nullable<int> _A4;
		
		private System.Nullable<decimal> _B;
		
		private System.Nullable<decimal> _C;
		
		private System.Nullable<decimal> _D;
		
		private System.Nullable<decimal> _E;
		
		private System.Nullable<decimal> _F;
		
		public Report_KappaDatapullingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FY", DbType="NVarChar(20)")]
		public string FY
		{
			get
			{
				return this._FY;
			}
			set
			{
				if ((this._FY != value))
				{
					this._FY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategory", DbType="NVarChar(255)")]
		public string SubCategory
		{
			get
			{
				return this._SubCategory;
			}
			set
			{
				if ((this._SubCategory != value))
				{
					this._SubCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationID", DbType="Int")]
		public System.Nullable<int> ApplicationID
		{
			get
			{
				return this._ApplicationID;
			}
			set
			{
				if ((this._ApplicationID != value))
				{
					this._ApplicationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIProjectLeader", DbType="NVarChar(255)")]
		public string PIProjectLeader
		{
			get
			{
				return this._PIProjectLeader;
			}
			set
			{
				if ((this._PIProjectLeader != value))
				{
					this._PIProjectLeader = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KappaType", DbType="NVarChar(50)")]
		public string KappaType
		{
			get
			{
				return this._KappaType;
			}
			set
			{
				if ((this._KappaType != value))
				{
					this._KappaType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> A1
		{
			get
			{
				return this._A1;
			}
			set
			{
				if ((this._A1 != value))
				{
					this._A1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> A2
		{
			get
			{
				return this._A2;
			}
			set
			{
				if ((this._A2 != value))
				{
					this._A2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A3", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> A3
		{
			get
			{
				return this._A3;
			}
			set
			{
				if ((this._A3 != value))
				{
					this._A3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A4", DbType="Int")]
		public System.Nullable<int> A4
		{
			get
			{
				return this._A4;
			}
			set
			{
				if ((this._A4 != value))
				{
					this._A4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this._B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this._C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> F
		{
			get
			{
				return this._F;
			}
			set
			{
				if ((this._F != value))
				{
					this._F = value;
				}
			}
		}
	}
	
	public partial class Report_KappaAvg_ByQCWeeks_NewResult
	{
		
		private string _QC_week;
		
		private string _IQ_StartDate;
		
		private string _IQ_EndDate;
		
		private string _Kappa;
		
		private System.Nullable<int> _E7F6Ct;
		
		private System.Nullable<int> _Number_Abs;
		
		private string _A1;
		
		private string _A2;
		
		private string _A3;
		
		private string _D;
		
		private string _E;
		
		private string _F;
		
		private string _Weekly_Avg;
		
		public Report_KappaAvg_ByQCWeeks_NewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_week", DbType="NVarChar(20)")]
		public string QC_week
		{
			get
			{
				return this._QC_week;
			}
			set
			{
				if ((this._QC_week != value))
				{
					this._QC_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_StartDate", DbType="NVarChar(50)")]
		public string IQ_StartDate
		{
			get
			{
				return this._IQ_StartDate;
			}
			set
			{
				if ((this._IQ_StartDate != value))
				{
					this._IQ_StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_EndDate", DbType="NVarChar(50)")]
		public string IQ_EndDate
		{
			get
			{
				return this._IQ_EndDate;
			}
			set
			{
				if ((this._IQ_EndDate != value))
				{
					this._IQ_EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kappa", DbType="VarChar(10)")]
		public string Kappa
		{
			get
			{
				return this._Kappa;
			}
			set
			{
				if ((this._Kappa != value))
				{
					this._Kappa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E7F6Ct", DbType="Int")]
		public System.Nullable<int> E7F6Ct
		{
			get
			{
				return this._E7F6Ct;
			}
			set
			{
				if ((this._E7F6Ct != value))
				{
					this._E7F6Ct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number_Abs", DbType="Int")]
		public System.Nullable<int> Number_Abs
		{
			get
			{
				return this._Number_Abs;
			}
			set
			{
				if ((this._Number_Abs != value))
				{
					this._Number_Abs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1", DbType="NVarChar(30)")]
		public string A1
		{
			get
			{
				return this._A1;
			}
			set
			{
				if ((this._A1 != value))
				{
					this._A1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2", DbType="NVarChar(30)")]
		public string A2
		{
			get
			{
				return this._A2;
			}
			set
			{
				if ((this._A2 != value))
				{
					this._A2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A3", DbType="NVarChar(30)")]
		public string A3
		{
			get
			{
				return this._A3;
			}
			set
			{
				if ((this._A3 != value))
				{
					this._A3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="NVarChar(30)")]
		public string D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="NVarChar(30)")]
		public string E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F", DbType="NVarChar(30)")]
		public string F
		{
			get
			{
				return this._F;
			}
			set
			{
				if ((this._F != value))
				{
					this._F = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekly_Avg", DbType="NVarChar(30)")]
		public string Weekly_Avg
		{
			get
			{
				return this._Weekly_Avg;
			}
			set
			{
				if ((this._Weekly_Avg != value))
				{
					this._Weekly_Avg = value;
				}
			}
		}
	}
	
	public partial class Report_AbstractSummaryResult
	{
		
		private string _FY;
		
		private string _Category;
		
		private string _Prevention_vs_5u0025;
		
		private System.Nullable<int> _Total_abstracts_loaded_into_PACT;
		
		private System.Nullable<int> _Total_number_abstracts_coded_by_IQ_coders__1N_;
		
		private string _u0025_abstracts_coded_by_IQ_coders__1N_;
		
		private System.Nullable<int> _Total_number_abstracts_coded_by_ODP__2N_;
		
		private string _u0025_of_total_abstracts_coded_by_ODP__2N_;
		
		private string _u0025_of_IQ_coded_abtracts_coded_by_ODP;
		
		private System.Nullable<int> _Total_number_of_uncoded_abstracts_remaning;
		
		private string _u0025_of_abstracts_that_are_uncoded;
		
		public Report_AbstractSummaryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FY", DbType="NVarChar(20)")]
		public string FY
		{
			get
			{
				return this._FY;
			}
			set
			{
				if ((this._FY != value))
				{
					this._FY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(255)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Prevention vs 5u0025]", Storage="_Prevention_vs_5u0025", DbType="NVarChar(50)")]
		public string Prevention_vs_5u0025
		{
			get
			{
				return this._Prevention_vs_5u0025;
			}
			set
			{
				if ((this._Prevention_vs_5u0025 != value))
				{
					this._Prevention_vs_5u0025 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total abstracts loaded into PACT]", Storage="_Total_abstracts_loaded_into_PACT", DbType="Int")]
		public System.Nullable<int> Total_abstracts_loaded_into_PACT
		{
			get
			{
				return this._Total_abstracts_loaded_into_PACT;
			}
			set
			{
				if ((this._Total_abstracts_loaded_into_PACT != value))
				{
					this._Total_abstracts_loaded_into_PACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total number abstracts coded by IQ coders (1N)]", Storage="_Total_number_abstracts_coded_by_IQ_coders__1N_", DbType="Int")]
		public System.Nullable<int> Total_number_abstracts_coded_by_IQ_coders__1N_
		{
			get
			{
				return this._Total_number_abstracts_coded_by_IQ_coders__1N_;
			}
			set
			{
				if ((this._Total_number_abstracts_coded_by_IQ_coders__1N_ != value))
				{
					this._Total_number_abstracts_coded_by_IQ_coders__1N_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[u0025 abstracts coded by IQ coders (1N)]", Storage="_u0025_abstracts_coded_by_IQ_coders__1N_", DbType="NVarChar(20)")]
		public string u0025_abstracts_coded_by_IQ_coders__1N_
		{
			get
			{
				return this._u0025_abstracts_coded_by_IQ_coders__1N_;
			}
			set
			{
				if ((this._u0025_abstracts_coded_by_IQ_coders__1N_ != value))
				{
					this._u0025_abstracts_coded_by_IQ_coders__1N_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total number abstracts coded by ODP (2N)]", Storage="_Total_number_abstracts_coded_by_ODP__2N_", DbType="Int")]
		public System.Nullable<int> Total_number_abstracts_coded_by_ODP__2N_
		{
			get
			{
				return this._Total_number_abstracts_coded_by_ODP__2N_;
			}
			set
			{
				if ((this._Total_number_abstracts_coded_by_ODP__2N_ != value))
				{
					this._Total_number_abstracts_coded_by_ODP__2N_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[u0025 of total abstracts coded by ODP (2N)]", Storage="_u0025_of_total_abstracts_coded_by_ODP__2N_", DbType="NVarChar(20)")]
		public string u0025_of_total_abstracts_coded_by_ODP__2N_
		{
			get
			{
				return this._u0025_of_total_abstracts_coded_by_ODP__2N_;
			}
			set
			{
				if ((this._u0025_of_total_abstracts_coded_by_ODP__2N_ != value))
				{
					this._u0025_of_total_abstracts_coded_by_ODP__2N_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[u0025 of IQ coded abtracts coded by ODP]", Storage="_u0025_of_IQ_coded_abtracts_coded_by_ODP", DbType="NVarChar(20)")]
		public string u0025_of_IQ_coded_abtracts_coded_by_ODP
		{
			get
			{
				return this._u0025_of_IQ_coded_abtracts_coded_by_ODP;
			}
			set
			{
				if ((this._u0025_of_IQ_coded_abtracts_coded_by_ODP != value))
				{
					this._u0025_of_IQ_coded_abtracts_coded_by_ODP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total number of uncoded abstracts remaning]", Storage="_Total_number_of_uncoded_abstracts_remaning", DbType="Int")]
		public System.Nullable<int> Total_number_of_uncoded_abstracts_remaning
		{
			get
			{
				return this._Total_number_of_uncoded_abstracts_remaning;
			}
			set
			{
				if ((this._Total_number_of_uncoded_abstracts_remaning != value))
				{
					this._Total_number_of_uncoded_abstracts_remaning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[u0025 of abstracts that are uncoded]", Storage="_u0025_of_abstracts_that_are_uncoded", DbType="NVarChar(20)")]
		public string u0025_of_abstracts_that_are_uncoded
		{
			get
			{
				return this._u0025_of_abstracts_that_are_uncoded;
			}
			set
			{
				if ((this._u0025_of_abstracts_that_are_uncoded != value))
				{
					this._u0025_of_abstracts_that_are_uncoded = value;
				}
			}
		}
	}
	
	public partial class Report_AbstractSummary_MergeResult
	{
		
		private string _FY;
		
		private string _Prevention_vs_5u0025;
		
		private System.Nullable<int> _Total_abstracts_loaded_into_PACT;
		
		private System.Nullable<int> _Total_number_abstracts_coded_by_IQ_coders__1N_;
		
		private string _u0025_abstracts_coded_by_IQ_coders__1N_;
		
		private System.Nullable<int> _Total_number_abstracts_coded_by_ODP__2N_;
		
		private string _u0025_of_total_abstracts_coded_by_ODP__2N_;
		
		private string _u0025_of_IQ_coded_abtracts_coded_by_ODP;
		
		private System.Nullable<int> _Total_number_of_uncoded_abstracts_remaning;
		
		private string _u0025_of_abstracts_that_are_uncoded;
		
		public Report_AbstractSummary_MergeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FY", DbType="NVarChar(20)")]
		public string FY
		{
			get
			{
				return this._FY;
			}
			set
			{
				if ((this._FY != value))
				{
					this._FY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Prevention vs 5u0025]", Storage="_Prevention_vs_5u0025", DbType="NVarChar(200)")]
		public string Prevention_vs_5u0025
		{
			get
			{
				return this._Prevention_vs_5u0025;
			}
			set
			{
				if ((this._Prevention_vs_5u0025 != value))
				{
					this._Prevention_vs_5u0025 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total abstracts loaded into PACT]", Storage="_Total_abstracts_loaded_into_PACT", DbType="Int")]
		public System.Nullable<int> Total_abstracts_loaded_into_PACT
		{
			get
			{
				return this._Total_abstracts_loaded_into_PACT;
			}
			set
			{
				if ((this._Total_abstracts_loaded_into_PACT != value))
				{
					this._Total_abstracts_loaded_into_PACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total number abstracts coded by IQ coders (1N)]", Storage="_Total_number_abstracts_coded_by_IQ_coders__1N_", DbType="Int")]
		public System.Nullable<int> Total_number_abstracts_coded_by_IQ_coders__1N_
		{
			get
			{
				return this._Total_number_abstracts_coded_by_IQ_coders__1N_;
			}
			set
			{
				if ((this._Total_number_abstracts_coded_by_IQ_coders__1N_ != value))
				{
					this._Total_number_abstracts_coded_by_IQ_coders__1N_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[u0025 abstracts coded by IQ coders (1N)]", Storage="_u0025_abstracts_coded_by_IQ_coders__1N_", DbType="NVarChar(20)")]
		public string u0025_abstracts_coded_by_IQ_coders__1N_
		{
			get
			{
				return this._u0025_abstracts_coded_by_IQ_coders__1N_;
			}
			set
			{
				if ((this._u0025_abstracts_coded_by_IQ_coders__1N_ != value))
				{
					this._u0025_abstracts_coded_by_IQ_coders__1N_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total number abstracts coded by ODP (2N)]", Storage="_Total_number_abstracts_coded_by_ODP__2N_", DbType="Int")]
		public System.Nullable<int> Total_number_abstracts_coded_by_ODP__2N_
		{
			get
			{
				return this._Total_number_abstracts_coded_by_ODP__2N_;
			}
			set
			{
				if ((this._Total_number_abstracts_coded_by_ODP__2N_ != value))
				{
					this._Total_number_abstracts_coded_by_ODP__2N_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[u0025 of total abstracts coded by ODP (2N)]", Storage="_u0025_of_total_abstracts_coded_by_ODP__2N_", DbType="NVarChar(20)")]
		public string u0025_of_total_abstracts_coded_by_ODP__2N_
		{
			get
			{
				return this._u0025_of_total_abstracts_coded_by_ODP__2N_;
			}
			set
			{
				if ((this._u0025_of_total_abstracts_coded_by_ODP__2N_ != value))
				{
					this._u0025_of_total_abstracts_coded_by_ODP__2N_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[u0025 of IQ coded abtracts coded by ODP]", Storage="_u0025_of_IQ_coded_abtracts_coded_by_ODP", DbType="NVarChar(20)")]
		public string u0025_of_IQ_coded_abtracts_coded_by_ODP
		{
			get
			{
				return this._u0025_of_IQ_coded_abtracts_coded_by_ODP;
			}
			set
			{
				if ((this._u0025_of_IQ_coded_abtracts_coded_by_ODP != value))
				{
					this._u0025_of_IQ_coded_abtracts_coded_by_ODP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total number of uncoded abstracts remaning]", Storage="_Total_number_of_uncoded_abstracts_remaning", DbType="Int")]
		public System.Nullable<int> Total_number_of_uncoded_abstracts_remaning
		{
			get
			{
				return this._Total_number_of_uncoded_abstracts_remaning;
			}
			set
			{
				if ((this._Total_number_of_uncoded_abstracts_remaning != value))
				{
					this._Total_number_of_uncoded_abstracts_remaning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[u0025 of abstracts that are uncoded]", Storage="_u0025_of_abstracts_that_are_uncoded", DbType="NVarChar(20)")]
		public string u0025_of_abstracts_that_are_uncoded
		{
			get
			{
				return this._u0025_of_abstracts_that_are_uncoded;
			}
			set
			{
				if ((this._u0025_of_abstracts_that_are_uncoded != value))
				{
					this._u0025_of_abstracts_that_are_uncoded = value;
				}
			}
		}
	}
	
	public partial class Report_KappaAvg_DataDetail_ByQCWeeks_NewResult
	{
		
		private string _QC_week;
		
		private string _IQ_StartDate;
		
		private string _IQ_EndDate;
		
		private string _FY;
		
		private System.Nullable<int> _Type;
		
		private string _Mechanism;
		
		private System.Nullable<int> _Appl_ID;
		
		private string _PI_Name;
		
		private System.Nullable<decimal> _A1;
		
		private System.Nullable<decimal> _A2;
		
		private System.Nullable<decimal> _A3;
		
		private System.Nullable<decimal> _D;
		
		private System.Nullable<decimal> _E;
		
		private System.Nullable<decimal> _F;
		
		public Report_KappaAvg_DataDetail_ByQCWeeks_NewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QC_week", DbType="NVarChar(20)")]
		public string QC_week
		{
			get
			{
				return this._QC_week;
			}
			set
			{
				if ((this._QC_week != value))
				{
					this._QC_week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_StartDate", DbType="NVarChar(50)")]
		public string IQ_StartDate
		{
			get
			{
				return this._IQ_StartDate;
			}
			set
			{
				if ((this._IQ_StartDate != value))
				{
					this._IQ_StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQ_EndDate", DbType="NVarChar(50)")]
		public string IQ_EndDate
		{
			get
			{
				return this._IQ_EndDate;
			}
			set
			{
				if ((this._IQ_EndDate != value))
				{
					this._IQ_EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FY", DbType="NVarChar(20)")]
		public string FY
		{
			get
			{
				return this._FY;
			}
			set
			{
				if ((this._FY != value))
				{
					this._FY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mechanism", DbType="NVarChar(20)")]
		public string Mechanism
		{
			get
			{
				return this._Mechanism;
			}
			set
			{
				if ((this._Mechanism != value))
				{
					this._Mechanism = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Appl_ID", DbType="Int")]
		public System.Nullable<int> Appl_ID
		{
			get
			{
				return this._Appl_ID;
			}
			set
			{
				if ((this._Appl_ID != value))
				{
					this._Appl_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PI_Name", DbType="NVarChar(255)")]
		public string PI_Name
		{
			get
			{
				return this._PI_Name;
			}
			set
			{
				if ((this._PI_Name != value))
				{
					this._PI_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> A1
		{
			get
			{
				return this._A1;
			}
			set
			{
				if ((this._A1 != value))
				{
					this._A1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> A2
		{
			get
			{
				return this._A2;
			}
			set
			{
				if ((this._A2 != value))
				{
					this._A2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A3", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> A3
		{
			get
			{
				return this._A3;
			}
			set
			{
				if ((this._A3 != value))
				{
					this._A3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> F
		{
			get
			{
				return this._F;
			}
			set
			{
				if ((this._F != value))
				{
					this._F = value;
				}
			}
		}
	}
	
	public partial class Report_SelectionDatapullingResult
	{
		
		private string _FY;
		
		private System.Nullable<int> _ApplicationID;
		
		private string _Category;
		
		private string _SubCategory;
		
		private string _ML_v1_3_prev_only_03_2017;
		
		private string _ML_v1_3_and_RCDC_prev_03_2017;
		
		private string _ML_v1_3_FY12toFY16_DataSet;
		
		private string _PIProjectLeader;
		
		private string _MainSection;
		
		private string _SubSection;
		
		private string _SectionName;
		
		private System.Nullable<short> _Final_Consensus;
		
		public Report_SelectionDatapullingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FY", DbType="NVarChar(20)")]
		public string FY
		{
			get
			{
				return this._FY;
			}
			set
			{
				if ((this._FY != value))
				{
					this._FY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationID", DbType="Int")]
		public System.Nullable<int> ApplicationID
		{
			get
			{
				return this._ApplicationID;
			}
			set
			{
				if ((this._ApplicationID != value))
				{
					this._ApplicationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(255)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategory", DbType="NVarChar(255)")]
		public string SubCategory
		{
			get
			{
				return this._SubCategory;
			}
			set
			{
				if ((this._SubCategory != value))
				{
					this._SubCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ML_v1_3_prev_only_03_2017", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ML_v1_3_prev_only_03_2017
		{
			get
			{
				return this._ML_v1_3_prev_only_03_2017;
			}
			set
			{
				if ((this._ML_v1_3_prev_only_03_2017 != value))
				{
					this._ML_v1_3_prev_only_03_2017 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ML_v1_3_and_RCDC_prev_03_2017", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ML_v1_3_and_RCDC_prev_03_2017
		{
			get
			{
				return this._ML_v1_3_and_RCDC_prev_03_2017;
			}
			set
			{
				if ((this._ML_v1_3_and_RCDC_prev_03_2017 != value))
				{
					this._ML_v1_3_and_RCDC_prev_03_2017 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ML_v1_3_FY12toFY16_DataSet", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ML_v1_3_FY12toFY16_DataSet
		{
			get
			{
				return this._ML_v1_3_FY12toFY16_DataSet;
			}
			set
			{
				if ((this._ML_v1_3_FY12toFY16_DataSet != value))
				{
					this._ML_v1_3_FY12toFY16_DataSet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIProjectLeader", DbType="NVarChar(255)")]
		public string PIProjectLeader
		{
			get
			{
				return this._PIProjectLeader;
			}
			set
			{
				if ((this._PIProjectLeader != value))
				{
					this._PIProjectLeader = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainSection", DbType="NVarChar(255)")]
		public string MainSection
		{
			get
			{
				return this._MainSection;
			}
			set
			{
				if ((this._MainSection != value))
				{
					this._MainSection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubSection", DbType="NVarChar(255)")]
		public string SubSection
		{
			get
			{
				return this._SubSection;
			}
			set
			{
				if ((this._SubSection != value))
				{
					this._SubSection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionName", DbType="NVarChar(255)")]
		public string SectionName
		{
			get
			{
				return this._SectionName;
			}
			set
			{
				if ((this._SectionName != value))
				{
					this._SectionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Final Consensus]", Storage="_Final_Consensus", DbType="SmallInt")]
		public System.Nullable<short> Final_Consensus
		{
			get
			{
				return this._Final_Consensus;
			}
			set
			{
				if ((this._Final_Consensus != value))
				{
					this._Final_Consensus = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
