<?xml version="1.0" encoding="utf-8"?><Database Name="ODP_Taxonomy_Dev" Class="ReportingAppDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=2sql235;Initial Catalog=ODP_Taxonomy_Dev;Persist Security Info=True;User ID=odpTaxonomy" SettingsObjectName="ODPTaxonomyDAL_ST.Properties.Settings" SettingsPropertyName="ODP_Taxonomy_DEVConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Report_QC_Week" Member="Report_QC_Weeks">
    <Type Name="Report_QC_Week">
      <Column Name="QC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QC_week" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Dates_IQ_Coded" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Rpt_Year" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rpt_Month" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Report_AbstractSummary" Method="Report_AbstractSummary">
    <ElementType Name="Report_AbstractSummaryResult">
      <Column Name="FY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="[Prevention vs 5u0025]" Member="Prevention_vs_5u0025" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Total abstracts loaded into PACT]" Member="Total_abstracts_loaded_into_PACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Total number abstracts coded by IQ coders (1N)]" Member="Total_number_abstracts_coded_by_IQ_coders__1N_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[u0025 abstracts coded by IQ coders (1N)]" Member="u0025_abstracts_coded_by_IQ_coders__1N_" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="[Total number abstracts coded by ODP (2N)]" Member="Total_number_abstracts_coded_by_ODP__2N_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[u0025 of total abstracts coded by ODP (2N)]" Member="u0025_of_total_abstracts_coded_by_ODP__2N_" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="[u0025 of IQ coded abtracts coded by ODP]" Member="u0025_of_IQ_coded_abtracts_coded_by_ODP" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="[Total number of uncoded abstracts remaning]" Member="Total_number_of_uncoded_abstracts_remaning" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[u0025 of abstracts that are uncoded]" Member="u0025_of_abstracts_that_are_uncoded" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Report_KappaAvg_ByQCWeeks" Method="Report_KappaAvg_ByQCWeeks">
    <Parameter Name="QCStartWeek" Parameter="qCStartWeek" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="QCEndWeek" Parameter="qCEndWeek" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="KType" Parameter="kType" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="Report_KappaAvg_ByQCWeeksResult">
      <Column Name="QC_week" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IQ_StartDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IQ_EndDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Kappa" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="E7F6Ct" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Number_Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="A1" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="A2" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="A3" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="B" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="C" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="D" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="E" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Weekly_Avg" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Report_KappaAvg_DataDetail_ByQCWeeks" Method="Report_KappaAvg_DataDetail_ByQCWeeks">
    <Parameter Name="QCStartWeek" Parameter="qCStartWeek" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="QCEndWeek" Parameter="qCEndWeek" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="KType" Parameter="kType" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="Report_KappaAvg_DataDetail_ByQCWeeksResult">
      <Column Name="QC_week" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IQ_StartDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IQ_EndDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AbstractID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Appl_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PI_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A1" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="A2" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="A3" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="B" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="C" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="D" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="E" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="F" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Report_SelectionDatapulling" Method="Report_SelectionDatapulling">
    <ElementType Name="Report_SelectionDatapullingResult">
      <Column Name="FY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PIProjectLeader" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MainSection" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubSection" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SectionName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Final Consensus]" Member="Final_Consensus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>