<?xml version="1.0" encoding="utf-8"?><Database Name="ODP_Taxonomy_DEV" Class="ReportDataLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=2sql235.iq.iqsolutions.com;Initial Catalog=ODP_Taxonomy_DEV;Persist Security Info=True;User ID=odpTaxonomy" SettingsObjectName="ODPTaxonomyReportDAL.Properties.Settings" SettingsPropertyName="ODP_Taxonomy_DEVConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.rpt_IQCode_Abstracts_Consensus_ByDate" Method="rpt_IQCode_Abstracts_Consensus_ByDate">
    <Parameter Name="DateStart" Parameter="dateStart" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DateEnd" Parameter="dateEnd" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="rpt_IQCode_Abstracts_Consensus_ByDateResult">
      <Column Name="Date" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GroupUsers" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="[Flagged Y/N]" Member="Flagged_Y_N" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Appl ID]" Member="Appl_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[PI Name]" Member="PI_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="A1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="A2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="A3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="B" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="C" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="D" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="E" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="F" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.rpt_IQCode_Abstracts_ByDate" Method="rpt_IQCode_Abstracts_ByDate">
    <Parameter Name="DateStart" Parameter="dateStart" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DateEnd" Parameter="dateEnd" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="rpt_IQCode_Abstracts_ByDateResult">
      <Column Name="Mechanism" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupUsers" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="[Flagged Y/N]" Member="Flagged_Y_N" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Appl ID]" Member="Appl_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[PI Name]" Member="PI_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Category" Method="Select_Category">
    <ElementType Name="Select_CategoryResult">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Coding" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Report_SelectionDatapulling_PIVOT" Method="Report_SelectionDatapulling_PIVOT">
    <Parameter Name="FY" Parameter="fY" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="Report_SelectionDatapulling_PIVOTResult">
      <Column Name="FY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="AbstractID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApplicationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[A-1-1-R-Alcohol]" Member="A_1_1_R_Alcohol" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-2-R-Alzheimer-disease]" Member="A_1_2_R_Alzheimer_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-3-R-Blank]" Member="A_1_3_R_Blank" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-4-R-Blood-disorder]" Member="A_1_4_R_Blood_disorder" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-5-R-Blood-pressure]" Member="A_1_5_R_Blood_pressure" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-6-R-Cancer]" Member="A_1_6_R_Cancer" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-7-R-Chemical/toxin]" Member="A_1_7_R_Chemical_toxin" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-8-R-Cholesterol]" Member="A_1_8_R_Cholesterol" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-9-R-Diabetes]" Member="A_1_9_R_Diabetes" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-10-R-Diet/nutrition]" Member="A_1_10_R_Diet_nutrition" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-11-R-Education/counseling]" Member="A_1_11_R_Education_counseling" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-12-R-Firearms]" Member="A_1_12_R_Firearms" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-13-R-Gastrointestinal-disease]" Member="A_1_13_R_Gastrointestinal_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-14-R-Genetics]" Member="A_1_14_R_Genetics" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-15-R-Healthcare-delivery]" Member="A_1_15_R_Healthcare_delivery" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-16-R-Heart-disease]" Member="A_1_16_R_Heart_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-17-R-HRQOL-Health-related-quality-of-life]" Member="A_1_17_R_HRQOL_Health_related_quality_of_life" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-18-R-Infectious-disease]" Member="A_1_18_R_Infectious_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-19-R-Kidney-disease]" Member="A_1_19_R_Kidney_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-20-R-Lung-disease]" Member="A_1_20_R_Lung_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-21-R-Maternal/paternal/child-health]" Member="A_1_21_R_Maternal_paternal_child_health" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-22-R-Medication/device]" Member="A_1_22_R_Medication_device" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-23-R-Mental-health]" Member="A_1_23_R_Mental_health" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-24-R-Microbiome]" Member="A_1_24_R_Microbiome" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-25-R-Mortality]" Member="A_1_25_R_Mortality" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-26-R-Motor-vehicle-crash]" Member="A_1_26_R_Motor_vehicle_crash" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-27-R-Musculoskeletal-disease]" Member="A_1_27_R_Musculoskeletal_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-28-R-Neurological-disease-not-Alzheimer]" Member="A_1_28_R_Neurological_disease_not_Alzheimer" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-29-R-Obesity]" Member="A_1_29_R_Obesity" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-30-R-Physical-activity]" Member="A_1_30_R_Physical_activity" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-31-R-Policy/built-environment]" Member="A_1_31_R_Policy_built_environment" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-32-R-Pneumonia/influenza]" Member="A_1_32_R_Pneumonia_influenza" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-33-R-Sexual-behavior]" Member="A_1_33_R_Sexual_behavior" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-34-R-Stress]" Member="A_1_34_R_Stress" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-35-R-Stroke]" Member="A_1_35_R_Stroke" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-36-R-Substance-abuse]" Member="A_1_36_R_Substance_abuse" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-37-R-Suicide]" Member="A_1_37_R_Suicide" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-38-R-Surgery]" Member="A_1_38_R_Surgery" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-39-R-Tobacco]" Member="A_1_39_R_Tobacco" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-40-R-Unintentional-injuries]" Member="A_1_40_R_Unintentional_injuries" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-41-R-Vaccine]" Member="A_1_41_R_Vaccine" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-42-R-Violence]" Member="A_1_42_R_Violence" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-1-43-R-Other-or-unclear]" Member="A_1_43_R_Other_or_unclear" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-1-E-Alcohol]" Member="A_2_1_E_Alcohol" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-2-E-Alzheimer-disease]" Member="A_2_2_E_Alzheimer_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-3-E-Blank]" Member="A_2_3_E_Blank" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-4-E-Blood-disorder]" Member="A_2_4_E_Blood_disorder" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-5-E-Blood-pressure]" Member="A_2_5_E_Blood_pressure" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-6-E-Cancer]" Member="A_2_6_E_Cancer" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-7-E-Chemical/toxin]" Member="A_2_7_E_Chemical_toxin" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-8-E-Cholesterol]" Member="A_2_8_E_Cholesterol" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-9-E-Diabetes]" Member="A_2_9_E_Diabetes" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-10-E-Diet/nutrition]" Member="A_2_10_E_Diet_nutrition" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-11-E-Education/counseling]" Member="A_2_11_E_Education_counseling" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-12-E-Firearms]" Member="A_2_12_E_Firearms" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-13-E-Gastrointestinal-disease]" Member="A_2_13_E_Gastrointestinal_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-14-E-Genetics]" Member="A_2_14_E_Genetics" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-15-E-Healthcare-delivery]" Member="A_2_15_E_Healthcare_delivery" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-16-E-Heart-disease]" Member="A_2_16_E_Heart_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-17-E-HRQOL-Health-related-quality-of-life]" Member="A_2_17_E_HRQOL_Health_related_quality_of_life" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-18-E-Infectious-disease]" Member="A_2_18_E_Infectious_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-19-E-Kidney-disease]" Member="A_2_19_E_Kidney_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-20-E-Lung-disease]" Member="A_2_20_E_Lung_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-21-E-Maternal/paternal/child-health]" Member="A_2_21_E_Maternal_paternal_child_health" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-22-E-Medication/device]" Member="A_2_22_E_Medication_device" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-23-E-Mental-health]" Member="A_2_23_E_Mental_health" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-24-E-Microbiome]" Member="A_2_24_E_Microbiome" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-25-E-Mortality]" Member="A_2_25_E_Mortality" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-26-E-Motor-vehicle-crash]" Member="A_2_26_E_Motor_vehicle_crash" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-27-E-Musculoskeletal-disease]" Member="A_2_27_E_Musculoskeletal_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-28-E-Neurological-disease-not-Alzheimer]" Member="A_2_28_E_Neurological_disease_not_Alzheimer" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-29-E-Obesity]" Member="A_2_29_E_Obesity" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-30-E-Physical-activity]" Member="A_2_30_E_Physical_activity" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-31-E-Policy/built-environment]" Member="A_2_31_E_Policy_built_environment" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-32-E-Pneumonia/influenza]" Member="A_2_32_E_Pneumonia_influenza" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-33-E-Sexual-behavior]" Member="A_2_33_E_Sexual_behavior" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-34-E-Stress]" Member="A_2_34_E_Stress" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-35-E-Stroke]" Member="A_2_35_E_Stroke" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-36-E-Substance-abuse]" Member="A_2_36_E_Substance_abuse" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-37-E-Suicide]" Member="A_2_37_E_Suicide" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-38-E-Surgery]" Member="A_2_38_E_Surgery" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-39-E-Tobacco]" Member="A_2_39_E_Tobacco" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-40-E-Unintentional-injuries]" Member="A_2_40_E_Unintentional_injuries" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-41-E-Vaccine]" Member="A_2_41_E_Vaccine" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-42-E-Violence]" Member="A_2_42_E_Violence" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-2-43-E-Other-or-unclear]" Member="A_2_43_E_Other_or_unclear" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-1-O-Alcohol]" Member="A_3_1_O_Alcohol" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-2-O-Alzheimer-disease]" Member="A_3_2_O_Alzheimer_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-3-O-Blank]" Member="A_3_3_O_Blank" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-4-O-Blood-disorder]" Member="A_3_4_O_Blood_disorder" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-5-O-Blood-pressure]" Member="A_3_5_O_Blood_pressure" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-6-O-Cancer]" Member="A_3_6_O_Cancer" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-7-O-Chemical/toxin]" Member="A_3_7_O_Chemical_toxin" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-8-O-Cholesterol]" Member="A_3_8_O_Cholesterol" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-9-O-Diabetes]" Member="A_3_9_O_Diabetes" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-10-O-Diet/nutrition]" Member="A_3_10_O_Diet_nutrition" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-11-O-Education/counseling]" Member="A_3_11_O_Education_counseling" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-12-O-Firearms]" Member="A_3_12_O_Firearms" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-13-O-Gastrointestinal-disease]" Member="A_3_13_O_Gastrointestinal_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-14-O-Genetics]" Member="A_3_14_O_Genetics" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-15-O-Healthcare-delivery]" Member="A_3_15_O_Healthcare_delivery" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-16-O-Heart-disease]" Member="A_3_16_O_Heart_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-17-O-HRQOL-Health-related-quality-of-life]" Member="A_3_17_O_HRQOL_Health_related_quality_of_life" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-18-O-Infectious-disease]" Member="A_3_18_O_Infectious_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-19-O-Kidney-disease]" Member="A_3_19_O_Kidney_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-20-O-Lung-disease]" Member="A_3_20_O_Lung_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-21-O-Maternal/paternal/child-health]" Member="A_3_21_O_Maternal_paternal_child_health" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-22-O-Medication/device]" Member="A_3_22_O_Medication_device" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-23-O-Mental-health]" Member="A_3_23_O_Mental_health" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-24-O-Microbiome]" Member="A_3_24_O_Microbiome" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-25-O-Mortality]" Member="A_3_25_O_Mortality" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-26-O-Motor-vehicle-crash]" Member="A_3_26_O_Motor_vehicle_crash" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-27-O-Musculoskeletal-disease]" Member="A_3_27_O_Musculoskeletal_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-28-O-Neurological-disease-not-Alzheimer]" Member="A_3_28_O_Neurological_disease_not_Alzheimer" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-29-O-Obesity]" Member="A_3_29_O_Obesity" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-30-O-Physical-activity]" Member="A_3_30_O_Physical_activity" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-31-O-Policy/built-environment]" Member="A_3_31_O_Policy_built_environment" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-32-O-Pneumonia/influenza]" Member="A_3_32_O_Pneumonia_influenza" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-33-O-Sexual-behavior]" Member="A_3_33_O_Sexual_behavior" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-34-O-Stress]" Member="A_3_34_O_Stress" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-35-O-Stroke]" Member="A_3_35_O_Stroke" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-36-O-Substance-abuse]" Member="A_3_36_O_Substance_abuse" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-37-O-Suicide]" Member="A_3_37_O_Suicide" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-38-O-Surgery]" Member="A_3_38_O_Surgery" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-39-O-Tobacco]" Member="A_3_39_O_Tobacco" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-40-O-Unintentional-injuries]" Member="A_3_40_O_Unintentional_injuries" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-41-O-Vaccine]" Member="A_3_41_O_Vaccine" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-42-O-Violence]" Member="A_3_42_O_Violence" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[A-3-43-O-Other-or-unclear]" Member="A_3_43_O_Other_or_unclear" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[B-1-Animals]" Member="B_1_Animals" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[B-2-Cells/cell lines]" Member="B_2_Cells_cell_lines" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[B-3-Blank]" Member="B_3_Blank" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[B-4-Human subjects]" Member="B_4_Human_subjects" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[B-5-Blank]" Member="B_5_Blank" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[B-6-Tissues/organs]" Member="B_6_Tissues_organs" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[B-7-Other-or-unclear]" Member="B_7_Other_or_unclear" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[C-1-Community]" Member="C_1_Community" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[C-2-Healthcare]" Member="C_2_Healthcare" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[C-3-Research-clinic-or-laboratory]" Member="C_3_Research_clinic_or_laboratory" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[C-4-Other-or-unclear]" Member="C_4_Other_or_unclear" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-1-Incarcerated/institutionalized]" Member="D_1_Incarcerated_institutionalized" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-2-LGBTI]" Member="D_2_LGBTI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-3-Low-income]" Member="D_3_Low_income" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-4-Military/veterans]" Member="D_4_Military_veterans" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-5-Older-adults/elderly]" Member="D_5_Older_adults_elderly" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-6-People-with-disabilities]" Member="D_6_People_with_disabilities" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-7-Pregnant-and/or-post-partum-women]" Member="D_7_Pregnant_and_or_post_partum_women" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-8-Rural]" Member="D_8_Rural" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-9-Urban]" Member="D_9_Urban" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-10-Youth-infants-children-adolescents]" Member="D_10_Youth_infants_children_adolescents" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[D-11-Other-or-unclear]" Member="D_11_Other_or_unclear" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[E-1-Analysis-of-existing-data]" Member="E_1_Analysis_of_existing_data" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[E-2-Methods-research]" Member="E_2_Methods_research" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[E-3-Non-randomized-intervention study]" Member="E_3_Non_randomized_intervention_study" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[E-4-Observational-study]" Member="E_4_Observational_study" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[E-5-Pilot/feasibility/proof-of-concept/safety]" Member="E_5_Pilot_feasibility_proof_of_concept_safety" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[E-6-Randomized-intervention-study]" Member="E_6_Randomized_intervention_study" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[E-7-Other-or-unclear]" Member="E_7_Other_or_unclear" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[F-1-Preventing-new-health-condition]" Member="F_1_Preventing_new_health_condition" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[F-2-Screening-for-risk-factor]" Member="F_2_Screening_for_risk_factor" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[F-3-Screening-for-early-disease]" Member="F_3_Screening_for_early_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[F-4-Preventing-progression-of-disease]" Member="F_4_Preventing_progression_of_disease" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[F-5-Methods-research]" Member="F_5_Methods_research" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[F-6-Other-or-unclear]" Member="F_6_Other_or_unclear" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>